import os  
import sqlite3  
import psycopg  
from psycopg import sql  
from dotenv import load_dotenv

load_dotenv()

SQLITE_DB = "campus_inventory.db"  
DATABASE_URL = os.getenv("DATABASE_URL")  

if not DATABASE_URL:  
    raise RuntimeError("DATABASE_URL is not set.")  

sqlite_conn = sqlite3.connect(SQLITE_DB)  
sqlite_conn.row_factory = sqlite3.Row  
pg_conn = psycopg.connect(DATABASE_URL)  
pg_conn.autocommit = False  

try:  
    pg_cur = pg_conn.cursor()  
    sqlite_cur = sqlite_conn.cursor()  
    
    table_definitions = {  
        "users": [  
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  
            "username TEXT UNIQUE NOT NULL",  
            "email TEXT UNIQUE NOT NULL",  
            "password_hash TEXT NOT NULL",  
            "role TEXT NOT NULL",  
            "failed_attempts INTEGER DEFAULT 0",  
            "is_locked BOOLEAN DEFAULT FALSE",
            "account_status TEXT DEFAULT 'Active'"
        ],  
        "password_resets": [  
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  
            "username TEXT NOT NULL",  
            "new_password_hash TEXT NOT NULL",  
            "status TEXT DEFAULT 'Pending'",  
            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"  
        ],  
        "hardware": [  
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  
            "item_name TEXT NOT NULL",  
            "category TEXT NOT NULL",  
            "quantity INTEGER NOT NULL",  
            "unit_price REAL NOT NULL",  
            "status TEXT NOT NULL",  
        ],  
        "transactions": [  
            "trans_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  
            "item_id INTEGER",
            "username TEXT",  
            "qty INTEGER",  
            "timeframe TEXT",  
            "status TEXT DEFAULT 'Pending'",  
            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        ],  
    }  

    # 1. Create tables if they don't exist
    for table_name, columns in table_definitions.items():  
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)  
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)  
        pg_cur.execute(create_sql)  

    counts = {}  
    # 2. Transfer the data
    for table_name, columns in table_definitions.items():  
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))  
        destination_count = pg_cur.fetchone()[0]  
        
        if destination_count > 0:  
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")  
            
        # CORRECTED LINE: Using a standard f-string for SQLite
        sqlite_cur.execute(f"SELECT * FROM {table_name}")  
        rows = sqlite_cur.fetchall()  
        counts[table_name] = len(rows)  
        
        if not rows:  
            continue  
            
        source_columns = [description[0] for description in sqlite_cur.description]  
        
        column_identifiers = sql.SQL(", ").join(sql.Identifier(column) for column in source_columns)  
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in source_columns)  
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(sql.Identifier(table_name), column_identifiers, placeholders)  
        
        for row in rows:  
            values = list(row)
            # Cast the integer 1 or 0 to boolean for the users table is_locked column
            if table_name == "users":
                is_locked_index = source_columns.index("is_locked")
                values[is_locked_index] = bool(values[is_locked_index])

            pg_cur.execute(insert_sql, values)  

    # 3. Update the sequences so new items don't throw primary key errors
    sequence_columns = {  
        "users": "id",  
        "password_resets": "id",  
        "hardware": "item_id",  
        "transactions": "trans_id",  
    }  

    for table_name, id_column in sequence_columns.items():  
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0) + 1, false) FROM {}").format(  
            sql.Literal(table_name),  
            sql.Literal(id_column),  
            sql.Identifier(id_column),  
            sql.Identifier(table_name),  
        )  
        pg_cur.execute(sequence_sql)  

    pg_conn.commit()  
    print("Migration completed successfully.")  
    print(f"  users:             {counts['users']}")  
    print(f"  password_resets:   {counts['password_resets']}")  
    print(f"  hardware:          {counts['hardware']}")  
    print(f"  transactions:      {counts['transactions']}")  

except Exception as e:  
    pg_conn.rollback()  
    print(f"Migration Failed: {e}")
    raise  
finally:  
    sqlite_conn.close()  
    pg_conn.close()